/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provis9_praktikum1;

import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class futama extends javax.swing.JFrame {

    private String nama = "";
    /**
     * Creates new form futama
     */
    public futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntekan = new javax.swing.JButton();
        labeljudul = new javax.swing.JLabel();
        labelnama1 = new javax.swing.JLabel();
        labelnama2 = new javax.swing.JLabel();
        labelnama3 = new javax.swing.JLabel();
        labelnim = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        labelkelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btntekan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btntekan.setText("Tekan Saya");
        btntekan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntekanActionPerformed(evt);
            }
        });

        labeljudul.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labeljudul.setText("Hello");

        labelnama1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelnama1.setText("NIM     :");

        labelnama2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelnama2.setText("Nama :");

        labelnama3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelnama3.setText("Kelas :");

        labelnim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelnama3)
                        .addGap(100, 100, 100)
                        .addComponent(labelkelas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelnama2)
                        .addGap(98, 98, 98)
                        .addComponent(labelnama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelnama1)
                        .addGap(99, 99, 99)
                        .addComponent(labelnim))
                    .addComponent(labeljudul))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntekan)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labeljudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama1)
                    .addComponent(labelnim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama2)
                    .addComponent(labelnama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama3)
                    .addComponent(labelkelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btntekan)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntekanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntekanActionPerformed
        // TODO add your handling code here:
        labeljudul.setText("Hallo nama saya Vania Yulianti");
        if (nama.isEmpty() || nama.equals(""))
            JOptionPane.showMessageDialog(null, "Selamat anda berhasil mengubah label tersebut");
        nama = "Vania Yulianti M";
        labelnim.setText("10118363");
        labelnama.setText(nama);
        labelkelas.setText("IF-9");
    }//GEN-LAST:event_btntekanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new futama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntekan;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labelkelas;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnama1;
    private javax.swing.JLabel labelnama2;
    private javax.swing.JLabel labelnama3;
    private javax.swing.JLabel labelnim;
    // End of variables declaration//GEN-END:variables
}
